#!/bin/bash

code --install-extension aaron-bond.better-comments
code --install-extension anseki.vscode-color
code --install-extension bierner.markdown-preview-github-styles
code --install-extension christian-kohler.path-intellisense
code --install-extension chrmarti.regex
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cssho.vscode-svgviewer
code --install-extension cstrap.flask-snippets
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension felipecaputo.git-project-manager
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension guyskk.language-cython
code --install-extension humao.rest-client
code --install-extension IBM.output-colorizer
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension momoto.binary-viewer
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-pyright.pyright
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension mushan.vscode-paste-image
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension p1c2u.docker-compose
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension ryu1kn.partial-diff
code --install-extension shanoor.vscode-nginx
code --install-extension shardulm94.trailing-spaces
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
